(var [x y] [0 0])
(def house-visits @{})
(defn visit [] (put house-visits [x y] true))
(visit)
(each direction (file/read stdin :all)
    (and
        (case (keyword (string/from-bytes direction))
            :^ (+= y 1)
            :> (+= x 1)
            :v (-= y 1)
            :< (-= x 1)
        )
        (visit)
    )
)
(print (length house-visits))
