(import ./common :as t)
(var seating (t/parse (file/read stdin :all)))
(var previous nil)
(while (deep-not= previous seating)
    (prin "doing a round... ")
    (set previous seating)
    (set seating (t/do-round seating))
    (print (t/count-occupied seating))
)
