(def tree (get "#" 0))
(def ski-map (string/split "\n" (file/read stdin :all)))
(def height (length ski-map))
(def width (length (get ski-map 0)))
(var tree-count 0)
(var x 0)
(var y 0)
(while true
    (+= x 3)
    (%= x width)
    (+= y 1)
    (if (>= y height) (break))
    (def char (or (get (get ski-map y) x) (break)))
    (if (= char tree) (++ tree-count))
)
(print tree-count)
