(var valid 0)
(def passports (string/split "\n\n" (file/read stdin :all)))
(each passport passports
    (def t @{})
    (each kv (string/split " " (string/replace-all "\n" " " passport))
        (def [k v] (string/split ":" kv))
        (put t k v)
    )
    (if (and
        (get t "byr")
        (get t "iyr")
        (get t "eyr")
        (get t "hgt")
        (get t "hcl")
        (get t "ecl")
        (get t "pid")
    ) (++ valid))
)
(print valid)
